name: microfs
description: A minimal filesystem stored in a single binary container, implementing the package:file FileSystem interface.
version: 2.1.0
repository: https://github.com/James1345/microfs
homepage: https://hedgehogfortress.uk

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  file: ^7.0.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
